### ISSUE TITLE
Disabling confiscated items names and lores (or translating)

### ISSUE THREAD

**Issue by Volgeop** [kangarko/Confiscate#100]
Hi, would be nice if you add way to 1. Disable custom item name and lore of classic item, like it confiscated diamond block, but the name is "confiscated diamond block" and when I pick it from chest and wanna return it to player, it's still named like this. Or atleast it could get normal name when picking from confiscated chest.

2. Would be nice, if you implement also way to translate it (but disabling too please :D), so players could translate it for ex. "Zabavený <item_name>" - <Zabavený diamantový blok>, would be nice if it lowercast the first letter of item too.

If you won't implement this feature, then admins can't simply pick up items from chest and return them to players, they have to give it and then for ex. count how many stack and pieces are in chest, and then they have to get it to player. This way they just could grab it from chest and put it in player's inventory back, if it was confiscated by mistake.

And yes, old system could be modified, just add way to translate it to lang file and to config add way to disable naming of confiscated items.

**Comment by kangarko** [comment]
Thanks, I added the option to disable items being named / changed completely when confiscating.

**Comment by Volgeop** [comment]
But in chest could be information when it was confiscated, but when you take it from chest, then it should disappear.

**Comment by kangarko** [comment]
Sorry that is not possible unless we do modify the item.
