### ISSUE TITLE
Puring for days

### ISSUE THREAD

**Issue by Volgeop** [kangarko/Confiscate#102]
Hi, nice feature will be when you add way to option in configuration to pure chests in chest room after days. So if there won't be any new item in one chest for... 30 days, the chest will be removed and there could be placed another chest. This option couldn't be just for chests, but also for items in chest. So pure old items in chests, and when it will be empty, then remove whole chest. So in config could be something like:
pure-chests: XX days
pure-items: XX days

This feature will be useful when there will be sooo many of chests and you wanna to make it more clear, more space and remove inactive and old ones... because now you even can't destroy the chests that you checked... 

This is probably whole new feature, don't know if old system could be improved. But would be nice too id you maybe add way to config to delete chests after checking, so when you open chest and maybe click on some special item, or automatically close it, the chest will be removed. Option like: delete-checked-chests in config.

**Comment by kangarko** [comment]
Thanks, when I rewrite the system I can implement this.
