### ISSUE TITLE
Pure log entries

### ISSUE THREAD

**Issue by Volgeop** [kangarko/Confiscate#103]
Hi, would be nice if you add option to config to pure logs or just log entries after some period of time, for ex. something like:
pure-logs: 30 days

Will be useful when there's confiscated so many items and you have really big log... 

Yes, old system can be improved and modified to just check and filter old ones and then delete them. Probably just log entries, not whole log, because there's only one log.

**Comment by kangarko** [comment]
Thanks, when I rewrite the system I can implement this.
