### ISSUE TITLE
1.16.1: False positive

### ISSUE THREAD

**Issue by Volgeop** [kangarko/Confiscate#105]
Hi, I got false positive... there's message that she has just 149 diamonds, but above limit 256, so wtf? Look here https://imgur.com/a/qSGa7dM

**Comment by Volgeop** [comment]
@kangarko Could you try to fix this please? Happened more times.

**Comment by kangarko** [comment]
Support times are 1-4 days, only ping me if I don't reply within that time frame please.

You haven't followed our bug reporting guidelines, please upload your ZIP file with your settings.

**Comment by kangarko** [comment]
And also put ["scan"] to Debug to your settings.yml and report me the console output please when that happens.

**Comment by Volgeop** [comment]
[Confiscate.zip](https://github.com/kangarko/Confiscate/files/5069968/Confiscate.zip)
Here you go.

Will report again, when it happens.

**Comment by kangarko** [comment]
A nieje hráč Newcomer? Lebo tam máš menší limit:

![a](https://i.imgur.com/ro7Iqhc.png)

**Comment by Volgeop** [comment]
No, když to ukazuje v té originální zprávě normální limit, neměl by být newcommer. A ani opravdu nemá být, ale nevím, zda to počítá ten plugin sám od sebe, jakože zda bere jako nováčky i starší hráče, zda to počítá čas od nahození pl, nebo ze statistik.

Ale ani tak by to neměl být newcommer dle zprávy.

**Comment by kangarko** [comment]
Dnes večer vydám novú verziu, prosím nastav Debugger na ["scan"] a napíš mi správy z konzoly keď sa to stane. Malo by tam byť napísané:

![a](https://i.imgur.com/QVuWKPz.png)

**Comment by Volgeop** [comment]
Jellikož otevírání truhel atd. strašně laguje, i hráči si stěžují, tak už posílám výsledky debugu, je tam nějaký problém s meta daty, který by byl třeba opravit.... protože opravdu, ten debug jim lagoval otvírání truhel.
[confiscate_log.zip](https://github.com/kangarko/Confiscate/files/5080584/confiscate_log.zip)

Tady dokonce video od jedné hráčky http://leteckaposta.cz/231391225

**Comment by kangarko** [comment]
Dakujem za upozornenie, nastavil som debug zapisovanie na vedlajsie jadro servera, nemalo by to lagovat a tiez vylepsil tie debug spravy do dalsej verzie aby nespamovalo ked nic neberie, prosim este to nechaj zapnute na [scan] a posli mi log len s tymi datami, ked sa to stane s presne uvedenym datumom - v tom co si poslal je vela udajov, nevyznam sa v tom.

**Comment by kangarko** [comment]
Podla konzoli to zobralo 24 kusov co bolo na povolenym limitom 256.

[17:33:26] [Server thread/INFO]: [scan] Scanning DIAMOND above limit. Found: 280 pieces vs. 256 max allowed.
[17:33:26] [Server thread/INFO]: Sledování 24x Diamond hráče TynkaCZE nad limitem 256x

V tvojom configu hore mas limit 256x:

![a](https://i.imgur.com/qzAVRnw.png)

**Comment by Volgeop** [comment]
Ahá 😅 Já to chápal tak, že ten člověk měl 24 celkem, a limit byl tedy 256, tak jsem si říkal, že to bylo málo. Dobře, omlouvámm se, zřejmě je to správně.

Až na ten error, který se tam vyskytl. Ten dokážete opravit? Či je to chyba z CMI?

**Comment by kangarko** [comment]
Super som rad ze sme si to vysvetlili.

Je mi luto, error pochadza z CMI.
