### ISSUE TITLE
Performance issue check newcomers (only)

### ISSUE THREAD

**Issue by x1p** [kangarko/Confiscate#106]
###Situation:
I want confiscate to check new players and new players only.
When newcomers join they should be permitted to get/buy/possess dangerous stuff like lava.
Confiscates newcomers function can fix that.
But it comes at a very high price of performance.

##The problem:
Based on timings, I think confiscate works like this:
- scan inventory (on use/click etc.)
- if contains restricted item:
- check if player is newcomer.
- if so: confiscate

This causes checks on every player. This is OK, if every player needs to be checked anyway.
However: in my case, I want only to prevent stuff in newcomers.

##Suggestion:
My suggestion would be to check in a different order:
- check if player is newcomer.
- scan inventory (on use/click etc.)
- if contains restricted item
- if so: confiscate
This way it skips 95% of the players who do not meet the criteria.

Can this be done?

**Comment by kangarko** [comment]
Thank you, I was able to improve the scanning speed by 20-30% for now.
