### ISSUE TITLE
1.16.1: "Cannot remove 'Inventory Open Scan' as it is not in the map!" error flooding console

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/Confiscate#107]
This error is incessant, not sure what is even causing it:
from error.log:
https://pastebin.com/CP76xpv2

from latest.log:
https://pastebin.com/j8SKHuYz

version 2.5.3
Paper-135 (1.16.1)

**Comment by kangarko** [comment]
Thanks, will get fixed
