### ISSUE TITLE
1.16.1: 2.5.3 option not functioning.

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/Confiscate#108]
Label_Item: false

Set as of version 2.5.3

Recently confiscated item:
https://imgur.com/a/Xnk62uZ

Renamed, added lore... all sorts of additional things done to the item which defeats the purpose of this option which I certainly thought was to have it remedied and returned to the player without additional unnecessary modification.  This item - for example - was snatched for the mending 3 enchant... which I could easily convert to mending one and then hand back, except now... it's ruined.   

Conf 2.5.5
Paper-135 (1.16.1)

**Comment by kangarko** [comment]
I cannot reproduce, I will reupload a new version soon:

![a](https://i.imgur.com/ftn1EyP.png)

**Comment by mrcoffee1026** [comment]
With version 2.5.6: same thing:
![2020-08-24_12 07 32](https://user-images.githubusercontent.com/3322491/91068654-9a397000-e602-11ea-80c2-8991e0eca5ac.png)

**Comment by kangarko** [comment]
Please ZIP me your config file just in case. How did these items get confiscated?

**Comment by mrcoffee1026** [comment]
Probably during chest access.

[Confiscate.zip](https://github.com/kangarko/Confiscate/files/5131427/Confiscate.zip)

**Comment by kangarko** [comment]
You had the config option twice and the bottom one was on true:

![a](https://i.imgur.com/miVDWzN.png)
