### ISSUE TITLE
1.8.8: Issues with When_Clicking option in config.

### ISSUE THREAD

**Issue by Nrc0611** [kangarko/Confiscate#109]
Currently, it's not a big deal I just disabled it but if you set "When_Clicking: true" to true it will completely mess up golden apples and bows. Whenever u try to shoot a bow or eat a golden apple while looking at a block it glitches out like crazy. The golden apple has another issue if you eat it for a second and let go it will finish eating it but visually you won't look like you are eating it. This obviously is a huge issue for PvP based servers. To fix this as I said just set it to false, but thought I might as well put this as a bug.

**Comment by kangarko** [comment]
Thanks, however When_Clicking option will needless to say cause these, and many other issues. I will remove from the next version - it is not possible to fix those item-related issues.
