### ISSUE TITLE
1.16.3: Problem with spawner eggs

### ISSUE THREAD

**Issue by HgeX** [kangarko/Confiscate#110]
Hey! I've just updated Confiscate from **2.5.7** to **2.5.8** and received [this](https://pastebin.com/2wdMjZ9R) error on startup. I didn't change the config or anything, just swapped the jar files. In case you need it (I guess you'll) [here](https://pastebin.com/3YXcjPdN) is my configuration and [here](https://drive.google.com/file/d/163k5Zgw78WDwJl9w73WjhrYcuC1M0RME/view?usp=sharing) the Confiscate's folder.

As you can see, the `SHEEP_SPAWN_EGG` only appear at one spot in the whole config file, but Confiscate isn't able to start, because it detects this specific value twice (I guess?).

Some details:
**Minecraft version:** 1.16.3
**Server software:** Paper (git-Paper-191)
**Plugin version:** 2.5.8
**Other plugins:** AcceptTheRules, BlockParticles, BuildersUtilities, ChatControl, Citizens, CitizensCMD, Confiscate, DeluxeChat, DeluxeMenus, HolographicDisplays, JetsAntiAFKPro, LuckPerms, Multiverse-Core, ParancsKuld-SPIGOT, PlaceholderAPI, PlotSquared, ProtocolLib, Reactor, SkinsRestorer, spark, TAB-BukkitBridge, UltraBar, Vault, ViaBackwards, ViaVersion, WorldBorder, WorldEdit, WorldEditSUI, WorldGuard, WorldGuardExtraFlags

**Comment by kangarko** [comment]
Remove MONSTER_EGG, because this does not work on MC 1.13+ so we have to replace it to _sheep_ and so it is then duplicated.

**Comment by HgeX** [comment]
I see, thanks!
