### ISSUE TITLE
1.16.3: hacked potion filter not working

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/Confiscate#111]
Exactly that player had "hacked" creative - level potion that could kill on splash impact in survival, was not confiscated, killed the player they attacked.  Although I'm not entirely sure how they get the item to survival in the first place, they've taken several.

**Comment by kangarko** [comment]
Post me your settings.yml please

**Comment by mrcoffee1026** [comment]
Ok i'll put that and also can we do anything about items like THIS:
![2020-10-09_13 20 43](https://user-images.githubusercontent.com/3322491/95613214-976bd080-0a32-11eb-97a2-f93606451042.png)
Furthermore, it IS possible that confiscate actually is working on potions but a player here has apparently sorted out a workaround, both to confiscate and porting items into survival from creative.  I'm not entirely sure how their doing either but I BELIEVE he is "bypassing" confiscate - as he puts it - by simply holding the offending item in his hand or offhand... one if which (or neither) is being checked ever.  Please remove this file from the ticket once you've got it:
[settings.zip](https://github.com/kangarko/Confiscate/files/5356542/settings.zip)

**Comment by kangarko** [comment]
I understand, if you want I can add an option to scan the inventories per time internal, say every 5-15 seconds there will be a random scan. Would that work?

**Comment by mrcoffee1026** [comment]
I doubt it, they're actively using /home or /warp to make the transition from one place to another, and I do have the scan taking place on these commands so there has to be something that is not being scanned.  While in the world, this place could be a Slimefun backpack... as they don't register as an item having inventory and there's no command that's run to open them.  But the origin of the item would surely need to be creative where they could have pulled it from something like a saved toolbar.  How they get it from there and on into survival is what is a mystery to me unless there is something on their person which is not being scanned at all, and the only thing I can figure that being would be either hand as that would have been easy enough to overlook as hand slots and armor slots are not part of "inventory" in a normal way.

**Comment by kangarko** [comment]
Can you please try doing a quick test with your hypotheses? It'll save us time since I don't have that setup and then I can add some workaround checks for that.

**Comment by mrcoffee1026** [comment]
I did retest, it is checking hand/offhand/hat slots... only thing else I can imagine is the backpacks, which are disabled in creative so that doesn't really explain how they're doing it.  There might be a way to integrate with slimefun and scan the backpack contents, but just as likely they'd have the item out of there long before the data file had actually physically been updated.

The item I put in the screen shot above is not being found under any of those scans, and a person could use that approach for applying affects to bypass this plugin also.

**Comment by kangarko** [comment]
Thanks, I can leave scanning SlimeFun backpacks as a future implementation.

**Comment by kangarko** [comment]
Closing, see Overview
