### ISSUE TITLE
Some Minecraft Spawn Eggs doesnt work + Tons of errors

### ISSUE THREAD

**Issue by Hyronymos1337** [kangarko/Confiscate#112]
Some Spawn Eggs doens't get removed, for example: MAGMA_CUBE_SPAWN_EGG

Minecraft Server Version: 1.16.3
Minecraft Server Software: Tuinity (testet with latest paperspigot 1.16.3 aswell)

Plugin Version: Confiscate 2.5.8
My Settings.yml: https://pastebin.com/9wm5dg9H

Errors (i cant upload full server log, no errors on startup): https://pastebin.com/1MUzte6Z

**Comment by kangarko** [comment]
Thanks I will fix that!
