### ISSUE TITLE
1.16.4 - log error

### ISSUE THREAD

**Issue by prochedary** [kangarko/Confiscate#114]
Hi,

I use the last version of Confiscate (2.6.3) on mine Skyblock 1.16.4 yatopia server and it thor sometime some errors. Here it is.

https://www.pastebin.cz/en/p/g7Kzy1B

Nevím, jestli to něco rozbíjí, ale asi by to dělat nemělo.

A teď jsem si uvědomil, že to nemusím psát anglicky :D co už.

Děkuji za Váš čas
Radek Procházka

**Comment by kangarko** [comment]
Napisal som majitelovi Shop pluginu, ked mi dal licenciu tak to opravim, dakujem.
