### ISSUE TITLE
32k sharpness bypass error

### ISSUE THREAD

**Issue by isaaaccc** [kangarko/Confiscate#117]
When a 32k is in a shulker and it is opened all the 32ks are reverted to a normal sword. but, when you place a hopper below the shulker without opening the shulker the items from the shulker will go into the hopper as 32k sharpness swords. this allows for an easy bypass of illegal items because it isnt constantly updated its only updated when a player leaves or opens a storage container. 

https://user-images.githubusercontent.com/75710046/112580347-6a7a6280-8db3-11eb-9005-7f6de889a391.mp4

**Comment by kangarko** [comment]
Thanks, however we're not adding new features such as hopper check to Confiscate right now.
