### ISSUE TITLE
1.17.1: Player inventory editing does not work

### ISSUE THREAD

**Issue by catfishua** [kangarko/Confiscate#124]
1) Put your Minecraft version in the title.
1.17.1: Editing the inventory of a player who is offline on the server does not work

2) Inventory editing of a player who is offline does not work. The reason is that the PowerNBT plugin is not supported for a long time, if you are reading my ticket, please change the api nbt from PowerNBT to NBT API (here is the link https://www.spigotmc.org/resources/nbt-api.7939/)

**Comment by kangarko** [comment]
Thanks. There is a fork that's being updated: https://github.com/Focusvity/PowerNBT/releases However we do plan to migrate to NBTAPI, there's no ETA yet.
