### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by DuckCraftPvP** [kangarko/Confiscate#14]
Can you please add support for the following plugins?

- https://www.spigotmc.org/resources/legacyfactions.40122/
- https://www.spigotmc.org/resources/randompackage-gkits-tinkerer-enchanter-custom-enchants-fully-configurable.38501/

**Comment by kangarko** [comment]
Hello,

LegacyFactions does not provide a method for developers to get a Faction by location. I have opened an inquiry at https://github.com/redstone/LegacyFactions/issues/75

RandomPackage is a premium resource to which I don't have access. I don't see how this should be incompatible.

**Comment by DuckCraftPvP** [comment]
lol i posted this on the wrong wiki, I ment to post it to a anti cheat wiki. 

Also speaking of this, Can you update support for papi to support relational placeholders?
