### ISSUE TITLE
1.18.2: Confiscate doesn't load

### ISSUE THREAD

**Issue by Greazi-Times** [kangarko/Confiscate#141]
I have set up the plugin only when restarting or loading the server it keeps crashing the plugin.
I have tried looking over the config once again but I see no problems at all.

Error: https://paste.techscode.com/cayuredevi.md
My folder:
[Confiscate.tar.gz](https://github.com/kangarko/Confiscate/files/8779136/Confiscate.tar.gz)

**Comment by kangarko** [comment]
Thanks, I have fixed and the plugin works again! https://i.imgur.com/pUNwyFG.png
