### ISSUE TITLE
Remove all items if above the limit

### ISSUE THREAD

**Issue by adabugra** [kangarko/Confiscate#143]
Can you add a option to take the all items of player if if its above the limit. Some people duped on my server and they putted stacks of nethirites to chests and confiscates only takes 1-2 netherite.

**Comment by kangarko** [comment]
Sorry, right now you need to specify the name of each material name. You can try using ["*"] but if it fails, then it's unsupported.

**Comment by kangarko** [comment]
Thanks for your suggestion. I can have a look when I am back from holidays after June 21st
