### ISSUE TITLE
Log all opened chests from player

### ISSUE THREAD

**Issue by adabugra** [kangarko/Confiscate#146]
Hi can you add an feature to log chests opened by a player and show them in a list with coordinates. You can add an command like /chestlog (player) and store the data in a db file.
I am suggesting this because someone duped on my server and hidden some chests filled with all duped items and i want to learn where chests are.

**Comment by kangarko** [comment]
Thanks, sounds good. I can consider this when I am back home from holidays after June 21st.

**Comment by kangarko** [comment]
I am sorry, while this feature sounds good I simply have no time to implement this right now due to other priorities. I may return to this in the future :)
