### ISSUE TITLE
Paper 1.19: Angeschossen Lands plugin failing to load

### ISSUE THREAD

**Issue by dlong93** [kangarko/Confiscate#148]
**Situation**
When I add Confiscate to my plugins, it hooks into Lands and then after Confiscate is done loading Lands starts enabling but loses th ability to write and read to it's own database.db file

I removed Confiscate and the issue goes away, if possible I'd like to run Confiscate along with Lands.

**Console Log**
I've included the very start of the server loading up until Lands disables due to not being able to load up...if you don't see the issue and need to have the entire console from start to finish let me know.
https://pastebin.com/fTJS7zgr

**Comment by kangarko** [comment]
Investigating in 24h

**Comment by kangarko** [comment]
Thanks, I have tested this on the latest release and enabled MySQL in Lands plugin, did not face the issue. I believe it got fixed by underlying library changes. Thanks for your patience.
