### ISSUE TITLE
1.19.2: Plugin fails to load

### ISSUE THREAD

**Issue by Greazi-Times** [kangarko/Confiscate#152]
I have configured the plugin but somehow it keeps saying that there is something wrong I have now reconfigured the whole plugin several times from scratch and it doesn't seem to be able to load. I have done some yml verifications and they all seem to be good.
The error I am getting;
https://hastebin.com/ruragunale.md

My config;
https://hastebin.com/sopenajili.yaml

**Comment by Greazi-Times** [comment]
The plugin has created a new file called settings_old.yml but there is nothing in it.

**Comment by kangarko** [comment]
So sorry for the delay, can you test with the version I am attaching below? I can't reproduce any loading problem (https://i.imgur.com/AwVUF1u.png) on it (but I wasnt able to open your hastebin links, please use pastebin next time)
[Confiscate-3.3.6.zip](https://github.com/kangarko/Confiscate/files/9813720/Confiscate-3.3.6.zip)

**Comment by Greazi-Times** [comment]
I will send the config again in a pastebin.
And I will also try the version provided.

**Comment by Greazi-Times** [comment]
> So sorry for the delay, can you test with the version I am attaching below? I can't reproduce any loading problem (https://i.imgur.com/AwVUF1u.png) on it (but I wasnt able to open your hastebin links, please use pastebin next time) [Confiscate-3.3.6.zip](https://github.com/kangarko/Confiscate/files/9813720/Confiscate-3.3.6.zip)

Issue has been found.
Whe your set the newcommer list to [] (When you don't want to use it) you get an error same for the limits it gives an error.

quick question tho can I make it a blacklist so I remove all items except the once I want them to have?

**Comment by kangarko** [comment]
Thank you I will fix that!

**Comment by Greazi-Times** [comment]
> Thank you I will fix that!

Maybe just add an 'enable: ' option where you can enable the whole system.

**Comment by kangarko** [comment]
The will have made it work automatically if you set the key to [] or {}
