### ISSUE TITLE
Wrong amount of item bought via servern shop

### ISSUE THREAD

**Issue by razzeking** [kangarko/Confiscate#155]
1.20.1 paper

when players buy stuff, it only shows 1x everytime, which if i where to buy 10 cobblestone, it would only show one
however the amount paid seems to be correct still, it can be seen in the picture below

[Confiscate.zip](https://github.com/kangarko/Confiscate/files/12064500/Confiscate.zip)

![image](https://github.com/kangarko/Confiscate/assets/47952472/2ffd6b9e-31ce-405d-90b4-873fa191b7b8)

**Comment by kangarko** [comment]
Thanks, fixed.
