### ISSUE TITLE
ExcellentShop

### ISSUE THREAD

**Issue by Ryzz3nn** [kangarko/Confiscate#156]
add support for excellentshop to show when people buy stuff

**Comment by kangarko** [comment]
Unfortunately it's a premium plugin and I cannot see a public API on their page, try contacting them to add a transaction event in an API form so we can hook into it.

**Comment by Ryzz3nn** [comment]
ill check on it, can this be open in the meanwhile perhaps till we know, i can also provide the info i recive be asking them

**Comment by kangarko** [comment]
Sure you can just comment below, I will see it.

**Comment by Ryzz3nn** [comment]
the maker of the plugin said something about **VirtualShopTransactionEvent**

**Comment by kangarko** [comment]
Could you please try this version?

[Confiscate-3.5.3.zip](https://github.com/kangarko/Confiscate/files/12566246/Confiscate-3.5.3.zip)

**Comment by Ryzz3nn** [comment]
that one seems to work fine. i also notcied one time that prices from shopguiplus was wrong

**Comment by Ryzz3nn** [comment]
would it perhaps be possible to pull item names from excellent shop, say we have elevators on hour server thats named "Hiss" in the gui, currently when you buy it, it says White Sulker Box

**Comment by kangarko** [comment]
Thanks for reporting! Unfortunately that is a limit of the API of these plugins since they give us these information.
