### ISSUE TITLE
1.8.8 console spam error

### ISSUE THREAD

**Issue by Dweezy750** [kangarko/Confiscate#157]
We've this annoying spam in console, Potion settings are disabled in settings.yml

11.09 05:37:56 [Server] ERROR Confiscate 3.5.3 encountered a FoException! Please check your error.log and report this issue with the information in that file. Running NachoSpigot 1.8.8-R0.1-SNAPSHOT and Java 18.0.2.1
11.09 05:37:56 [Server] WARN [Confiscate] Task #91495 for Confiscate v3.5.3 generated an exception
11.09 05:37:56 [Server] INFO org.mineacademy.confiscate.lib.exception.FoException: Report: Unsupported material from item: POTION (41)
11.09 05:37:56 [Server] INFO at org.mineacademy.confiscate.lib.Valid.checkNotNull(Valid.java:59) ~[?:?]
11.09 05:37:56 [Server] INFO at org.mineacademy.confiscate.lib.remain.CompMaterial.fromItem(CompMaterial.java:2402) ~[?:?]
11.09 05:37:56 [Server] INFO at org.mineacademy.confiscate.model.Scan.scanAboveLimit0(Scan.java:577) ~[?:?]
11.09 05:37:56 [Server] INFO at org.mineacademy.confiscate.model.Scan.scanAboveLimit(Scan.java:527) ~[?:?]
11.09 05:37:56 [Server] INFO at org.mineacademy.confiscate.model.Scan.scanBannedItems(Scan.java:346) ~[?:?]
11.09 05:37:56 [Server] INFO at org.mineacademy.confiscate.model.Scan.scan(Scan.java:143) ~[?:?]
11.09 05:37:56 [Server] INFO at org.mineacademy.confiscate.model.Scan.scanInventory(Scan.java:118) ~[?:?]
11.09 05:37:56 [Server] INFO at org.mineacademy.confiscate.listener.ScanListener$1.run(ScanListener.java:134) ~[?:?]
11.09 05:37:56 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[server.jar:git-NachoSpigot-"5655b72"]
11.09 05:37:56 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [server.jar:git-NachoSpigot-"5655b72"]
11.09 05:37:56 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:793) [server.jar:git-NachoSpigot-"5655b72"]
11.09 05:37:56 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:398) [server.jar:git-NachoSpigot-"5655b72"]
11.09 05:37:56 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:723) [server.jar:git-NachoSpigot-"5655b72"]
11.09 05:37:56 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [server.jar:git-NachoSpigot-"5655b72"]
11.09 05:37:56 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by kangarko** [comment]
Please post me your settings.yml so I can try reproducing.

**Comment by Dweezy750** [comment]
[settings.zip](https://github.com/kangarko/Confiscate/files/12640182/settings.zip)

**Comment by kangarko** [comment]
Thanks, gonna fix tonight.
