### ISSUE TITLE
Confisgate plugin

### ISSUE THREAD

**Issue by zachary435** [kangarko/Confiscate#17]
Hello there 

I am wanting to buy this plugin but how can it stop staff from abusing there rank i am intrested how it detects it i will be using this plugin for a fraction server and a skyblock bungee network i did test it out it is nicly made also how many server are allowed to run it or is it restricted via a product key

**Comment by kangarko** [comment]
Hello and thank you for your interest!

You may run Confiscate on every server within your bungee network.

For your questions, I highly recommend you take a look at this quick article:
https://github.com/kangarko/Confiscate/wiki/Frequently-Asked-Questions

Thank you!

**Comment by kangarko** [comment]
I am closing this, if you have any more questions feel free to comment below!
