### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by renzotom** [kangarko/Confiscate#20]
I am suggesting make language file for:

- [ ] Commands

- [ ] Messages (like how to create room, etc.)

- [ ] Command to remove room

**Inventory view**

- [ ] To inventory view add also slots for armor + offhand.

- [ ] Permission to only view inventory, no edit!

- [ ] Permission to only view ender chest, no edit!

**Supports:**

- [x] Support for Residence protection (maybe there is, I only look on that page https://github.com/kangarko/Confiscate/wiki/Compatibility)

- [ ] Support for BossShop plugin

- [ ] Support for TradeMe plugin

**Configuration**

- [x] Typo here:     "Allow_Strictness: 1    "(there are free blanks, after number, by default)

- [x] I think, you can add that by default, in "Items_Survival:" ENDER_PORTAL, ENDER_PORTAL_FRAME, PORTAL and maybe more items like that

**Comment by kangarko** [comment]
Hey renzotom!

Thank you for your suggestions. I plan to add the language in the future.

I will add viewing armor content's into the next version.

The next version will also include a new "confiscate.commands.inv.write" permission required to edit inventory content. 

Support for BossShop and TradeMe plugins have been noted.

Thank you!

**Comment by renzotom** [comment]
Armor has also permissions? And what about add those permissions to permissions page?

**Comment by kangarko** [comment]
Just added: "confiscate.commands.inv.armor", thank you!
