### ISSUE TITLE
ShopGui+ logging error from confiscate

### ISSUE THREAD

**Issue by Fonzee9** [kangarko/Confiscate#21]
https://pastebin.com/s81cwZFz

**Comment by Fonzee9** [comment]
This also causes Confiscate to completely disable itself 😢

**Comment by Fonzee9** [comment]
I've downgraded Shopgui+ until this issue can be fixed.

**Comment by kangarko** [comment]
Hey!

I am sorry you have issues! Please tell me which ShopGUI+ version started to cause problems, and to which version you have downgraded to resolve it?

**Comment by Fonzee9** [comment]
1.11.0-SNAPSHOT has the problem i downgraded to 1.10.0-SNAPSHOT for now

**Comment by kangarko** [comment]
I have reviewed the code, and the developer made a mistake in their code. I have informed him, please wait for the next version and then I will update :) I am closing this because I am aware of the issue and it will get fixed soon.
