### ISSUE TITLE
New version of Confiscate breaks Worldedit limiter

### ISSUE THREAD

**Issue by Fonzee9** [kangarko/Confiscate#23]
Worldedit limiter wasn't working at all on newesr version so i downgraded to 1.5.8 to test if it'd work since i know i set it up right and it worked.

**Comment by kangarko** [comment]
How is it broken? May I see your settings.yml please?

**Comment by Fonzee9** [comment]
It is completely broken doesn't work at all almost like its disabled... downgrading fixed the issue for me 

https://pastebin.com/XjWbF5D0

**Comment by kangarko** [comment]
Please test out the latest version 1.6.1. There have literally been no changes from 1.5.8 till 1.6.0.

**Comment by Fonzee9** [comment]
I updated to 1.6.1 tested it worldedit limiter still didn't work then downgraded back to 1.5.8 and it worked again.
