### ISSUE TITLE
Creative Mode

### ISSUE THREAD

**Issue by x1p** [kangarko/Confiscate#25]
Situation:
A player is in creative mode
Setting: When_Clicking = true (row 42 in the settings file)

Player places normal blocks (Stone, wood etc). Every item that is placed will disappear from inventory as if in survival mode. So every item must me recalled from creative menu to place another block.

**Comment by kangarko** [comment]
Cannot reproduce, when having creative mode ignored:

![a](https://i.imgur.com/b5agepa.png)

**Comment by x1p** [comment]
I have Creative_mode set to false

**Comment by kangarko** [comment]
You have to have Ignore.Creative_Mode set to true in order to not get confiscated those items in Creative, otherwise they are going to be taken.

**Comment by x1p** [comment]
My question was about setting up creative mode server. Therefor creative mode should not be ignored. Had to solve this in another way.

**Comment by kangarko** [comment]
I understand now. In that case yes, you have to remove the items that are being taken from settings.yml to prevent that.
