### ISSUE TITLE
Crashable items question

### ISSUE THREAD

**Issue by x1p** [kangarko/Confiscate#26]
> Remove items that might cause the server or the client to crash?
> This includes technical blocks like piston head, that cannot be used anyway.
> Crashable_Items: true

Does this include chests with the "copy me" hack?

**Comment by kangarko** [comment]
The following blocks are included:

![a](https://i.imgur.com/ClfbgyO.png)

I think those chests are no longer functional when Confiscate is active, can you run a quick test with Wurst?

**Comment by x1p** [comment]
First of all, I am not familiar with crash chest. But I used such chest. It was not taken. I could place it. I could open it, use it like normal. Nothing happens: including no crash. I can see there is 1 nbt tag. It is not removed.

**Comment by kangarko** [comment]
Confiscate does not filter NBT tags because we do not hook into internal libraries.

I have tested, it seems that Spigot has patched it as it no longer works:
![a](https://i.imgur.com/6V8UDHd.png)
