### ISSUE TITLE
Clear Player Log

### ISSUE THREAD

**Issue by AshourAziz** [kangarko/Confiscate#31]
I was wondering if it would be possible to add a command to clear someones log as well as room. After we notice something abnormal our staff take action and then resolve the situation therefore we'd like to clear the logs that way we're able to easily keep track with issues as they arise instead of having to monitor 200+ chests.

**Comment by kangarko** [comment]
Would you like to clear the chests as well?

**Comment by AshourAziz** [comment]
When clearing the logs the chest should be cleared as well.

**Comment by kangarko** [comment]
We are not planning to include this feature due to works on other priorities.
