### ISSUE TITLE
Shop Spam

### ISSUE THREAD

**Issue by AshourAziz** [kangarko/Confiscate#32]
With several players on and a solid economy our admins are constantly spammed with shop buying/selling. Is it possible to make a permission node confiscate.notify.disableshop would disable shop notifications. Or you could add confiscate.notify.shop and then people could set this permission node to "false" in their permissions plugin to then disable receiving shop messages.

**Comment by kangarko** [comment]
https://github.com/kangarko/Confiscate/wiki/Frequently-Asked-Questions#how-can-i-disable-shoptransactionsbuy-sell-log-messages
