### ISSUE TITLE
Ignore/Confiscate Certain Name/Lore

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/Confiscate#35]
Confiscate can be set up to confisicate SPECIFIC Items so... it seems it would be ideal to run a check for an item I know would exist when using a bug in another plugin to create duplicated crate keys.  The "copies" are identical to the original in name and lore, but do not contain the original enchant (unbreaking 1).  The "key" is a tripwire hook.  Is there a way to have this plugin match specific lore / colored name... and not match if the correct enchant is also found... so as to remove the duplicate when it is found?

Like this?

```
  Items_Survival:
  - BEDROCK
  - TRIPWIRE_HOOK
    - name:&9Vote Crate Key
    - lore1:&7Right-Click on a "&9Vote&7" crate
    - lore2:&7to win an item!
    - lore3:

```

**Comment by kangarko** [comment]
Hey, great suggestion unfortunately I don't have time for it now, so I am leaving it for the future.

**Comment by ArtNRG** [comment]
Hope I found a good place for this text.
There are few items with broken texture. Here is an example: broken anvil. My players use a sand cannon to throw an anvil to GriefPrevention claim. After landing the anvil become an item with broken texture. You also can get it using command /item anvil:4 1 or /item anvil:5. 
[Screenshot](https://pasteboard.co/He7ZiR2.png)
I want to confiscate be able to remove those items (anvil:3, anvil:4 etc) without deleting all anvils.

**Comment by mrcoffee1026** [comment]
Same can be applied to like the non-decaying leaf ids... show as a checker texture in the inventory but a normal leaf block if you place it. (Id 18:4, for example)  Having this applied to additional item data does make a difference, I would like to see these capabilities expanded somewhat but I'm not sure if that would tremendously slow down scans and things.  However, a lot of items - including the leaves - are acquiring new item ids in 1.13 so may be easier to match their states using other features.

Block data 4-11 for the anvil referenced damage as well as orientation of the anvil as placed.  And yeah, these really shouldn't exist outside of the give command.  I agree it would be nice to have a thing just up and grab those.  I haven't done anything with block data specific stuff with this but it might be worth tinkering with the worldguard blacklist and see if they can be pinpointed and erased that way also.

**Comment by kangarko** [comment]
I can look into it when the new release is up and stable, but it must be backward compatible so yes, both support for data values and states makes sense. Okay for now this is open to the future as before.

**Comment by kangarko** [comment]
Feature in preparation.
