### ISSUE TITLE
Cannot eat/bow when looking a block

### ISSUE THREAD

**Issue by DaveDevil** [kangarko/Confiscate#37]
I have a problem, players said that when looking at a block (not necessarily a container) they can't eat or stretch the bow, seems like something interfere with the interaction with the right click.

With LuckPerm's verbose, I saw that when trying this, many confiscate.bypass permissions are checked.

This seems to happens every time I right click a block with an item in hand.

Admins having confiscate.bypass.inventory permissions are not affected by the interaction blocking

**Comment by kangarko** [comment]
It seems you have Scan.When_Clicking on true. Disable it. Scanning when clicking has a known bug and will be temporarily disabled in the next version.
