### ISSUE TITLE
Spam of console errors

### ISSUE THREAD

**Issue by CakeSlayer** [kangarko/Confiscate#40]
Been using the plugin for a while and seems to work as it does take items properly but it also spams console with the error messages below, My server is running Spigot 1.8.8 and I was using the Confiscate 1.7.7 version, Thinking it was an issue with outdated version, I updated to Confiscate 1.7.10 yet I still get console error spam. Any tips or suggestions for this?

https://hastebin.com/epekigunaw.vbs
https://hastebin.com/suparikilu.vbs

**Comment by kangarko** [comment]
Have you used PlugMan or any other reloader? That error may seem coming from that. Make sure you shut server down when updating and only using /c reload for reloading.
