### ISSUE TITLE
Room problem

### ISSUE THREAD

**Issue by AodX** [kangarko/Confiscate#42]
Hello, 
im using Confiscate and when i setup the room 
i made a world and named it " room "
i do /Confiscate room tool 
and i get the diamondAxe and then i select the floor with right click and it become Emerald 
and it says the room have been setup 
but then when i restarted my Server 
i got this in the Console 
https://hastebin.com/mobetuwobi.md
and the room won't be setup .-. i done the same thing again and its not setup still ...

if you gonna ask about Plugin, if i bought it or not, or how to prove that i did
i work for draexo, his SpigotMC page is ( https://www.spigotmc.org/members/draexo.2905/ ) 
you can message him and ask him about me ( im AodX ) 
he bought the plugin from you :+1: 
i told him to, since im his Developer in his server

Anyway, can you please tell me why im getting this problem ?
i tried to remove the room.db too and the whole Confiscate folder, but same 
hmmm :thinking: weird

**Comment by AodX** [comment]
can you help please ?

**Comment by kangarko** [comment]
I am sorry for the delay. I have fixed it by adding a new option: Room.Load_After_Server_Starts, please enable it in the next release.

**Comment by AodX** [comment]
When the next release gonna come ?

**Comment by kangarko** [comment]
In an hour.
