### ISSUE TITLE
Errors when trying to see logs

### ISSUE THREAD

**Issue by DarkLBP** [kangarko/Confiscate#45]
When I try to run these commands to show player logs I get some errors.

Executing: /c log stats anycategory
[error1.txt](https://github.com/kangarko/Confiscate/files/1877929/error1.txt)

Executing: /c log view anyplayer
[error2.txt](https://github.com/kangarko/Confiscate/files/1877930/error2.txt)

**Comment by kangarko** [comment]
Please wait for the next version and move your command-spy.log from logs/ folder to Confiscate/ folder. New log messages will appear there. Thank you.
