### ISSUE TITLE
Confiscate is not loading

### ISSUE THREAD

**Issue by SaF3rC** [kangarko/Confiscate#49]
Hi! I have a problem when Confiscate loads. My server's firewall is blocking all external connections in exception of allowed connections by me. The problem is that I need to know where is Confiscate connecting to allow that connection in my firewall but I do not find that. Can you provide me an IP, link or something to add it in my firewall? Thanks for your attention.

**Comment by kangarko** [comment]
Hello,

the domain is named kangarko.com, and its IP is 81.2.194.241 (but whitelist the domain preferably).

If that won't help, message me on SpigotMC.
