### ISSUE TITLE
Room Permission Issue

### ISSUE THREAD

**Issue by PerkusMaximus** [kangarko/Confiscate#50]
Heya!

So, i'm setting up permissions for and I wanted my moderators to be able to right-click on the signs above the chest, but they couldn't even though they had (confiscate.room.signs). It appears that they also need to permission (confiscate.room.open) to be able to use the feature, but I wanted my moderators to be able to right-click the sign, and not be able to open the chests.

Would it be possible to add that ability?

**Comment by kangarko** [comment]
Fixed. From now on, use confiscate.room.signs to right-click signs to view logs.
