### ISSUE TITLE
Confiscate 1.8.3 encountered a com2

### ISSUE THREAD

**Issue by ArtNRG** [kangarko/Confiscate#52]
error.log https://pastebin.com/raw/iDncyHf2
latest.log https://pastebin.com/raw/ENRE82Ug
settings.yml https://pastebin.com/raw/9xrLgvT0
The error appears while trying to confiscate this potion: https://cdn.pbrd.co/images/Hre5e9e.png

**Comment by kangarko** [comment]
Fixed.
