### ISSUE TITLE
Support documenting and logging players who mine too quickly

### ISSUE THREAD

**Issue by deadman96385** [kangarko/Confiscate#55]
Having a notifier of if a player has gotten for example 25 lapis ore within 20 minutes and having it tied into the confiscate so it logs it and has the option to take it/clone it into a chest would be super useful and I think a good fit for the plugin. It would help a lot with the people who xray on survival servers.

**Comment by kangarko** [comment]
Thank you. Right now we are not planning this but I can add this as a future idea.
