### ISSUE TITLE
The Plugin is disableing it self

### ISSUE THREAD

**Issue by Skyfighter1** [kangarko/Confiscate#57]
Hey, pls Help me.... The Plugin is disableing it self..... Error:

06.01 17:54:03 [Server] INFO [Confiscate] Enabling Confiscate v1.9.8
06.01 17:54:03 [Server] INFO ____ ____ _  _ ____ _ ____ ____ ____ ___ ____ 
06.01 17:54:03 [Server] INFO |    |  | |\ | |___ | [__  |    |__|  |  |___ 
06.01 17:54:03 [Server] INFO |___ |__| | \| |    | ___] |___ |  |  |  |___ 
06.01 17:54:04 [Server] INFO [Confiscate] Disabling Confiscate v1.9.8

What could I do?

(I use spigot 1.13.2 and I have the latest Confiscate version...)

My Plugins:
`LagAssist, 
DangerousNether, 
PlaceholderAPI, 
ReasonGM, 
IllegalStack, 
WorldBorder, 
EasyBackup, 
Multiverse-Core, 
ProtocolLib,
LibsDisguises, 
FastAsyncWorldEdit,
 DangerousCaves, 
EffectLib, 
Realistic_World, 
Vault, 
UltraPermissions, 
ProtocolSupport, 
TitleManager, 
CMI, 
Hydra, 
CMIEInjector, 
WorldEdit, 
FastAsyncVoxelSniper,
Feudal, 
Confiscate`

**Comment by kangarko** [comment]
Post me your entire startup log please.

**Comment by Skyfighter1** [comment]
Here is the Log: https://pastebin.com/nSf5nZEs

**Comment by Skyfighter1** [comment]
Pls help... I can´t use your plugin since 12 days....

**Comment by Eyremba** [comment]
> Pls help... I can´t use your plugin since 12 days....

@Skyfighter1 just re-download it and try it again.

If it is still not working, you can also report it to the SpigotMC staff.

**Comment by kangarko** [comment]
I have contacted you on Spigot.
