### ISSUE TITLE
[Question] Can the plugin scan custom inventories?

### ISSUE THREAD

**Issue by Leomelonseeds** [kangarko/Confiscate#66]
Hey there!

Before I buy this plugin, I would like to know if this plugin includes a feature to scan custom inventories. I am currently going through an economy reset and I want to scan Playervaults and Enderchests for illegal items.

Thanks in advance!

**Comment by kangarko** [comment]
Hello,

Confiscate is setup to ignore custom inventories because that would cause issues with menu systems and would remove items there.

Enderchests are scanned normally. 

Let me know if you have any more questions :)

Matej
