### ISSUE TITLE
Confiscate custom items exceeding a certain amount

### ISSUE THREAD

**Issue by Leomelonseeds** [kangarko/Confiscate#67]
Just like the title. I need to confiscate stacks of Iron Golem Spawners specifically. Is there any way I could do that?

**Comment by kangarko** [comment]
Hi,

I apology but for your certain case there is no way to catch those spawners, it must been another plugin that created them. Vanilla does not allow to label the spawner item with the mob it spawns, it always yields a pig unless there is some other plugin labeling them in its own unique way we cannot see.

Matej

**Comment by kangarko** [comment]
What plugin created them btw? Maybe I can add a special hook
