### ISSUE TITLE
Loved PowerNBT but...

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/Confiscate#68]
PowerNBT is required for offline inventory viewing... can you provide an alternative for this?  As PowerNBT does not work in 1.13 and as they've been sitting on unanswered 1.13 pull requests for just shy of a year now, it's pretty clear it isn't likely to ever be upgraded.  If not, fine, but since that's primarily the feature I'd use from this plugin, I may not use it anymore.

**Comment by kangarko** [comment]
Definitely.

I'm experimenting with NBTAPI in ChatControl and Boss unfortunately as you surely had noticed it caused some stability issues. When we are sure we achieved enterprise level stability with that library then I'll expand it over all plugins including Confiscate.

Thanks
