### ISSUE TITLE
Confiscate-added NBT data makes items unstackable

### ISSUE THREAD

**Issue by PsychoLynx** [kangarko/Confiscate#69]
Hello!
On our server, we have configured Confiscate to clone items and inform staff instead of confiscating the items. However, the cloning action (or at least some action related to players having more items than the limits) seems to add NBT tags to the items (in our  most recent case, diamonds), causing them to not stack with other items of the same kind. We do not have a chest room set up at the moment, so perhaps that could be the cause?

Is there anything to be done about this? We are using version 2.2.3. Our config is attached here: https://pastebin.com/UtiRNKTP

**Comment by kangarko** [comment]
Dear PsychoLynx,

I am very sorry I have to tell you that any modification to the item will make it unstackable with other items. This seems to be coded deep in the internals of the MC server. We have to add NBT tags to prevent those items being confiscated into the chest or admins warned multiple times.

I am leaving this open unfortunately this appears to be a long term issue.

Respectfully yours,
Matej

**Comment by kangarko** [comment]
Closing, after lots of research it cannot be fixed at the moment.

**Comment by PsychoLynx** [comment]
Well, thank you for your effort!
