### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by MaximumDesigns** [kangarko/Confiscate#7]
12.06 18:36:53 [Server] ERROR Could not pass event InventoryOpenEvent to Confiscate v1.2.0
12.06 18:36:53 [Server] INFO org.bukkit.event.EventException: null
12.06 18:36:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 18:36:53 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 18:36:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 18:36:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 18:36:53 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:755) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 18:36:53 [Server] INFO at net.minecraft.server.v1_12_R1.EntityPlayer.openContainer(EntityPlayer.java:786) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 18:36:53 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:195) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 18:36:53 [Server] INFO at com.Acrobot.Breeze.Utils.BlockUtil.openBlockGUI(BlockUtil.java:67) [ChestShop.jar:?]
12.06 18:36:53 [Server] INFO at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.showChestGUI(PlayerInteract.java:201) [ChestShop.jar:?]
12.06 18:36:53 [Server] INFO at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:88) [ChestShop.jar:?]
12.06 18:36:53 [Server] INFO at sun.reflect.GeneratedMethodAccessor173.invoke(Unknown Source) ~[?:?]
12.06 18:36:53 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
12.06 18:36:53 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
12.06 18:36:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 18:36:53 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 18:36:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 18:36:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 18:36:53 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 18:36:53 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:448) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 18:36:53 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:944) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 18:36:53 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 18:36:53 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 18:36:53 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 18:36:53 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
12.06 18:36:53 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
12.06 18:36:53 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 18:36:53 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]

**Comment by kangarko** [comment]
I cannot find Confiscate in the error stack, but only ChestShop.

Please send the error stack to the authors of the ChestShop plugin you're using.
