### ISSUE TITLE
Confiscate abnormal attributes

### ISSUE THREAD

**Issue by Fabrimat** [kangarko/Confiscate#70]
Player in creative can give themselves items with abnormal attributes, like a sword with speed +1000 that let you run all over the world making the server super laggy.
There shoud be a way to block unusual attributes or set a maximum value for each one.

**Comment by kangarko** [comment]
Thanks, counting as a suggestion. For now you can cap those attributes in your spigot.yml file. Names here: https://minecraft.gamepedia.com/Attribute

![a](https://i.imgur.com/qjp4rmS.png)

**Comment by JavaFactoryDev** [comment]
Hi!
Thanks so much for suggesting your feature/idea. We have carefully discussed it with our team and have concluded that, although interesting, it is at present, not a good fit nor we have the resources to add it in the near future. Feel free to re-suggest this feature in the future if you still have this problem

Regards
Leonhard from MineAcademy
