### ISSUE TITLE
Consfiscate removes dropped stone

### ISSUE THREAD

**Issue by jer3m01** [kangarko/Confiscate#72]
## Description
Whenever a player drops stone Confiscate will immediately remove the item.
This happens with all stone "based" block (all blocks with id = 1) since we're running on 1.8.8.

## Server Information
Paper: **1.8.8, Build #443**
Confiscate version: **2.2.5** *Seems to also affect prior releases (only tested 2.0.2)*

## More Info
It seems that the block item is an 'END_GATEWAY' when dropped as shown in this picture:
![image](https://user-images.githubusercontent.com/33844379/62413620-403dc500-b611-11e9-9eb5-bd6109a0d42e.png)

The same happens when mining stone w/ silk touch.

Other block don't seem to be affected.
Neither does holding stone in our inventory.

**Comment by kangarko** [comment]
Thanks, patched
