### ISSUE TITLE
About anti-cheating

### ISSUE THREAD

**Issue by BillZhucn** [kangarko/Confiscate#73]
[1.14.4-Baritone.zip](https://github.com/kangarko/Confiscate/files/3501933/1.14.4-Baritone.zip)
The clients can use this to cheat and this has the same effect as X-Ray. They can also have the effect like night_vision all the time.
![1b4890829042de8b](https://user-images.githubusercontent.com/53694134/63031430-84b94280-bee6-11e9-8661-cc0884ad5196.jpg)
This is the screenshot from a client who use this cheat app. Please help to prevent them to dig a large amount of luxury mines. Thanks!!!

**Comment by kangarko** [comment]
Thank you for a report, however Confiscate is not aimed to prevent this kind of cheating at the time. I am sorry about this, and you can install an additional plugin that's specially crafted against that kind of hacking.
