### ISSUE TITLE
Some problems in using Forge at the same time

### ISSUE THREAD

**Issue by ProperSAMA** [kangarko/Confiscate#74]
I've suffered a lot from mod bugs on several occasions.Confiscate seems to be very helpful to me, so I bought it.
But when I use it, I encounter some problems.Confiscate's support for mod items does not seem to be very good.
For example, when I open some Mod containers, Console displays such errors:
https://pastebin.com/fmab83ZG
I tried to add this item to Containers Ignore like this, but it didn't work.Then I tried to turn it off, but the error still occurred.
Logs: https://pastebin.com/CjuzXwKR
My config:
`Scan:
  Inventories: false
  When_Clicking: false
  On_Command:
  - /warp
  Containers:
    Enabled: **false**
    Ignored:
    - ANVIL
    - **BETTERRECORDS_RECORDETCHER**`

I tried to add mod items to "Items_Above".But no matter how I configure it, it won't work.
(like ADVANCED_SOLAR_PANELS:MACHINES:5 5)

This plug-in doesn't seem to support Mod items at all.But Mod causes more problems than Vanilla does.More need for this plugin.Is it possible to improve support for Mod servers in the future?
The server version is 1.12.2. CatServer is used.
(CatServer is similar to KCauldron, but it's 1.12.2)

**Comment by kangarko** [comment]
Hello,

Confiscate unfortunately does not support mods, it runs fine under Spigot or Paper but not on KCauldron. Let me know your paypal email and I can refund you.
