### ISSUE TITLE
Enderchests aren't scanned?

### ISSUE THREAD

**Issue by Foxxite** [kangarko/Confiscate#77]
It seems like enderchests aren't scanned for illegal items. Did I overlook something in the config or is this a bug:

Server version: Paper version git-Paper-209 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
Confiscate version: 2.2.9
Config: https://hastebin.com/siwinurexa.yml

Thanks for any help in advance.

**Comment by kangarko** [comment]
Hello,

please set Debug to ["*"] in settings.yml to enable debugging of all messages, then open a normal chest then ender chest and let me know the console messages from both cases.

**Comment by Foxxite** [comment]
**Chest:**
`
06.10 19:17:42 [Server] Server thread/INFO Scanning Kiylo's CHEST (Crafting)
06.10 19:17:42 [Server] Server thread/INFO Taking 49x of Kiylo's DIAMOND_BLOCK above limit 15x
06.10 19:17:42 [Server] Server thread/INFO ✉ To Kiylo: [06.10.2019 17:17:42] Confiscate has taken a Diamond Block (reason: above limit) from you at world [53, 71, -82]
`
**Enderchest:**
`
06.10 19:17:50 [Server] Server thread/INFO Ignoring ENDER_CHEST inventory with custom title (Crafting != Ender Chest)
`

None of the blocks **haven't** been renamed, so no idea where it gets the name Crafting from.

**Comment by kangarko** [comment]
It's some weird changes in the Spigot API, not your/mine fault. Will patch this soon thanks!
