### ISSUE TITLE
High Priority: Search for items by lore

### ISSUE THREAD

**Issue by itslukemango** [kangarko/Confiscate#82]
Can you make it search all items for a specific lore? It might be on different line numbers.

**Comment by JavaFactoryDev** [comment]
Hi itslukemango,

Thanks for your suggestion.
We may implement it in further releases.

Regards,
Leonhard from MineAcademy

**Comment by JavaFactoryDev** [comment]
Hi!
Thanks so much for suggesting your feature/idea. We have carefully discussed it with our team and have concluded that, although interesting, it is at present, not a good fit nor we have the resources to add it in the near future. Feel free to re-suggest this feature in the future if you still have this problem

Regards
Leonhard from MineAcademy
