### ISSUE TITLE
Items not being removed from inventories when using Bungee Playerdata sync plugins with redis or mysql 

### ISSUE THREAD

**Issue by Stixil** [kangarko/Confiscate#85]
Can there be a way to have the scanning of players inventories upon join be delayed a few seconds? There are some issues with items being duped when using bungee playerdata sync plugins. I think this would fix the issue for items to be removed after sync is completed instead of before. Thanks!

**Comment by JavaFactoryDev** [comment]
Hi Stixil,

I am so sorry for the delay - I didn't get notified.

Please follow #83 

Regards,
- Leonhard from MineAcademy
