### ISSUE TITLE
Offline inventory viewing using a plugin other than Power NBT

### ISSUE THREAD

**Issue by Stixil** [kangarko/Confiscate#86]
Power NBT is no longer updated for new servers, and it would be nice to have this feature with an updated library such as NBP API. Thanks!

**Comment by JavaFactoryDev** [comment]
Hi Stixil, 
thank you for providing this:)

Regards,
- Leonhard from MineAcademy

**Comment by JavaFactoryDev** [comment]
@kangarko

**Comment by kangarko** [comment]
Apology for my delay this time, we decided not to implement this right now because of other priorities, however I'll have a note to look into it in the future.
