### ISSUE TITLE
WorldEdit block limit is ignored

### ISSUE THREAD

**Issue by HgeX** [kangarko/Confiscate#87]
So I have WorldEdit hook enabled in my configuration, and the `Total_Blocks_Limit` works just fine, but the limit for individual blocks, not so much. The plugin gets enabled as expected with no errors whatsoever.

[This](https://hastebin.com/zizikatino.php) is how the config section looks like.

According to the configuration, one without confiscate.bypass should be able to place only 32 sponges at a time, however the operation completes every time, no matter how much sponge do I attempt to place. Blocks without any limit set, should be completely removed from any operation, but they are not.
*Basically the whole section is ignored, or I'm doing something seriously wrong... :/*

**Plugin version**: Confiscate 2.4.1
**WorldEdit version**: 7.1.0;8e55131
**Server version**: Paper-129 (MC 1.15.2)

**Plugins**:
`
AcceptTheRules, AntiAFKPro, BlockParticles, BuildersUtilities, ChatControl, Citizens, CitizensCMD, Confiscate, DeluxeMenus, FogusCore, HolographicDisplays, LiteChat, LuckPerms, Multiverse-Core, NuggetCore, ParancsKuld-SPIGOT, PlaceholderAPI, PlotSquared, ProtocolLib, ServerSigns, SkinsRestorer, spark, SunLight, SunLight_Economy, UltraBar, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldBorder, WorldEdit, WorldEditSUI, WorldGuard
`

**Comment by JavaFactoryDev** [comment]
Hi Hgex,

Please follow #83 

Regards,
- Leonhard from MineAcademy

**Comment by HgeX** [comment]
Uploaded the plugins folder to google drive, you can access it [here](https://drive.google.com/open?id=1cM-7lGpCTkkbSLq7IVSFyjE_RUOCOA9V)

**Comment by kangarko** [comment]
@JavaFactoryDev
