### ISSUE TITLE
Questions about config.

### ISSUE THREAD

**Issue by Callial** [kangarko/Confiscate#88]
Not a bug, just some questions I couldn't find an answer to. 

1st. Is there a way to delete certain items when they are confiscated. To put it simply we are running a creative server and players are abusing vanilla lingering potions to lag out other players. I would like to prevent this.
2nd. I am a bit confused about wildcards and how they work/if they work with this plugin. Could I, for example, take spawn eggs only if they have abnormal nbt data? We have people crashing the server by placing [These](http://prntscr.com/rjof3s) into dispensers. 
3rd and final. Does this plugin allow disabling of dispensers? I can't seem to find any up to date plugins that allow me to disable them from activating.

Thanks for your help in advance and I hope I put this in the right place.

**Comment by kangarko** [comment]
@JavaFactoryDev please reply

**Comment by JavaFactoryDev** [comment]
Hey Callial,

Thank you for asking this question here.

First of all, I am so sorry for the delay - I missed this.

1) Can you explain your first question further? What's the end goal, what are you trying to archive?

2) Can you tell me what exactly you mean by "wildcards" please?

3) Not as far as I know, but you could try to use worldguard for this.

Regards

**Comment by Callial** [comment]
Basically since the chest room doesn't stack upwards and we have a fair amount of players it quickly exceeds our plot boundaries. So we would like to be able to delete certain items outright when they are confiscated and only put specific ones into the chest system. Or just give us the ability to limit the width of the chest system and make it extend upwards or downwards.

By wildcards, we want to be able to allow players to use certain spawn eggs but remove any others, wildcards could be like "if it has lore with the word 'server'" remove it. this would remove all server creeper spawn eggs that are generated from hacked clients while still allowing players to use our furniture plugin. 

We did sucessfully use worldguard to prevent this :)

**Comment by kangarko** [comment]
@JavaFactoryDev

**Comment by JavaFactoryDev** [comment]
So basically, there is no way to limit the amounts of items confiscated. However you could just remove some chests if not needed anymore.
(Or move the room to a separate world)

Instead of wildcards, you could try to just log illegal items and decide urself whether you want to confiscate them or not.

**Comment by JavaFactoryDev** [comment]
Please reopen if needed.
