### ISSUE TITLE
Items_Newcomers creative bypass

### ISSUE THREAD

**Issue by x1p** [kangarko/Confiscate#89]
The "Items_Newcomers" function seems to work alright when new comers find the forbidden item by a chest. Even in creative mode.

However. When a new player is in creative mode, this can be bypassed by obtaining it directly by pressing "E" and grab the desired item.
A second way is if staff puts the item in his inventory with /invsee. This conflicts with the comment: `#so this might reveal abusive admins giving them items for free.` because staff primarily uses invsee.
So it seems containers are checked, not the inventory.

When the player somehow got hold of a lava bucket anyway, he is still able to place the contents of a bucket on right click, even though `When_Clicking` is enabled

I bought the plugin just because of this newcomer function.

Does confiscate degrade performance on (all) players that are not a newcomer anymore because of the checks performed on them? (In other words: is everyone checked when clicking then checked for newcomer, or first checked for newcomer, then checked on clicking?)

**Comment by JavaFactoryDev** [comment]
Hi x1p,

I am so sorry for the delay - I somehow didn't get notified.

Please follow #83 

Regards,
- Leonhard from MineAcademy
