### ISSUE TITLE
Plugin Confiscates Items "above limit" even though NO limits are set.

### ISSUE THREAD

**Issue by Feriixu** [kangarko/Confiscate#90]
As the title says, Confiscate is confiscating players Items, even though I removed all entries from the `Items_Above: ...`
and 
```
  Items_Newcomers:
    Threshold: 1 second
    List: ...
```
lists. It uses the example thresholds e.g.: 256xDIAMOND

**Comment by Feriixu** [comment]
Update:
Confiscate resets 
`Items_Above: ...`
and
```
Items_Newcomers:
    List: ...
```
back to default values if you delete them all. Why can't i just have NO entries in the list?

**Comment by kangarko** [comment]
@JavaFactoryDev please have a look

**Comment by Feriixu** [comment]
So I found out what the issue is: I don’t know how YAML works. An empty list in YAML is represented by 
`List: []..`
and if you use that it should work properly. Maybe add information about this in the files comments or the documentation?
