### ISSUE TITLE
Confiscate cannot recognize some spawner eggs

### ISSUE THREAD

**Issue by HgeX** [kangarko/Confiscate#91]
The title pretty much explains the situation. Addig any of the following materials to `Confiscate.Items` list will prevent the plugin from enabling or reloading correctly:

```
- WANDERING_TRADER_SPAWN_EGG
- TRADER_LLAMA_SPAWN_EGG
- COD_SPAWN_EGG
- PANDA_SPAWN_EGG
- FOX_SPAWN_EGG
- BEE_SPAWN_EGG
```

**Platform:** *Paper*
**Minecraft version:** *1.15.2*
**Details:** *https://pastebin.com/5DvsY7HG*
**Plugin settings:** *https://pastebin.com/Ve48SyQ3*

**Comment by JavaFactoryDev** [comment]
Hi HgeX,

I am so sorry for the delay - I somehow didn't get notified.

Please follow #83 

Regards,
- Leonhard from MineAcademy

**Comment by HgeX** [comment]
Uploaded the plugins folder to google drive, you can access it [here](https://drive.google.com/open?id=1cM-7lGpCTkkbSLq7IVSFyjE_RUOCOA9V)

**Comment by kangarko** [comment]
@JavaFactoryDev
