### ISSUE TITLE
Bypass on Wurst

### ISSUE THREAD

**Issue by Lexzach** [kangarko/Confiscate#92]
Wurst now has a built-in feature called "Crash Chest" it is basically a chest with the max nbt tags it can have. It actually does lag a server out, and Confiscate does not detect it and remove it.

Edit: It also has a mob egg built-in as well that doesn't get removed

**Comment by JavaFactoryDev** [comment]
Hi Vehzx,

I am so sorry for the delay - I somehow didn't get notified.

Thank you for providing this idea, we will consider adding this.

Regards,
- Leonhard from MineAcademy

**Comment by Lexzach** [comment]
Hello Can we please make it so it will take items if the player has gotten
x amount per hour. We just started getting real players on the server, and
this plugin keeps on taking away legit players items. It would also be cool
to add something that takes diamonds if they have *mined* x amount in x
amount of time. I have had too many situations where players team up in SMP
and open a really good players chest and all their diamonds get deleted. I
have had to just turn off the taking feature because it is causing way too
much trouble.

**Comment by kangarko** [comment]
@JavaFactoryDev

**Comment by JavaFactoryDev** [comment]
Hi!
Thanks so much for suggesting your feature/idea. We have carefully discussed it with our team and have concluded that, although interesting, it is at present, not a good fit nor we have the resources to add it in the near future. Feel free to re-suggest this feature in the future if you still have this problem

Regards
Leonhard from MineAcademy
