### ISSUE TITLE
error on load (could be other plugin interference)

### ISSUE THREAD

**Issue by Vehzx** [kangarko/Confiscate#93]
Hi, used to use confiscate alot last year sometime, after closing my server and coming back recently I tried loading the most up to date version into 1.15.2 paper and I get this message on startup.

https://pastebin.com/dW5kCgtc

This could be a problem with shopguiplus but I thought i'd ask here first, thanks.

**Comment by JavaFactoryDev** [comment]
Hi Vehzx,

I am so sorry for the delay - I somehow didn't get notified.

This is caused by the other plugin, please contact their support

Regards,
- Leonhard from MineAcademy
