### ISSUE TITLE
New Dupe detection system...

### ISSUE THREAD

**Issue by Lexzach** [kangarko/Confiscate#94]
Maybe add a system so the user can choose if it is x diamonds per hour instead of x diamonds total. I have had problems with players having their diamonds taken away, and I would love to choose to have a system that keeps track of how many diamonds are earned per hour as a combined anti-xray and anti-dupe system combined into one.

**Comment by kangarko** [comment]
@JavaFactoryDev

**Comment by JavaFactoryDev** [comment]
Hi!
Thanks so much for suggesting your feature/idea. We have carefully discussed it with our team and have concluded that, although interesting, it is at present not a good fit nor we have the resources to add it in the near future. Feel free to re-suggest this feature in the future if you still have this problem

Regards
Leonhard from MineAcademy
