### ISSUE TITLE
1.12: CONFISCATE - Custom Items

### ISSUE THREAD

**Issue by alexeses** [kangarko/Confiscate#95]
Hello!

I've been working for 2 days to figure out how I can get customs items. I mean, (https://prnt.sc/spi7wu), I've tried to put it in many ways but I can't think of anything. Could you give me a hand?

The name is "&7[&e*&7] &fPico &e&lMECANICO &7[&E*&7]" but it doesn't grab me in any way. The configuration is as follows -- https://prnt.sc/spi9ya

(Buyer: https://prnt.sc/spiivf)

[ERROR CONFISCATE.zip](https://github.com/kangarko/Confiscate/files/4696611/ERROR.CONFISCATE.zip)

**Comment by JavaFactoryDev** [comment]
Hi alexeses,

Thank you for asking this question here.

Can you please tell me more about what you mean by "get custom items".
Do you want to confiscate them?

P.S.
You don't need to assign me;)

Regards,
Leonhard from MineAcademy

**Comment by alexeses** [comment]
Hello!

Thank you very much for answering, yes, that's right, I want to get customs items but I put the name on it and it doesn't catch on. Is there any example of items with that name so I can get used to it? I've been trying for about 2 days and it doesn't work. I attached all the necessary files in my previous message.

Thank you very much for your reply.
