### ISSUE TITLE
1.15.2: Confiscate cannot recognize some spawner eggs 

### ISSUE THREAD

**Issue by HgeX** [kangarko/Confiscate#97]
The title pretty much explains the situation. Addig any of the following materials to `Confiscate.Items` list will prevent the plugin from enabling or reloading correctly:

```
- WANDERING_TRADER_SPAWN_EGG
- TRADER_LLAMA_SPAWN_EGG
- COD_SPAWN_EGG
- PANDA_SPAWN_EGG
- FOX_SPAWN_EGG
- BEE_SPAWN_EGG
```

**Platform:** *Paper (git-Paper-346)*
**Minecraft version:** *1.15.2*
**Details:** *https://pastebin.com/5DvsY7HG*
**Plugin version:** *2.4.1*
**Plugin settings:** *https://pastebin.com/Ve48SyQ3*

You can access the plugin's folder by clicking [here](https://drive.google.com/file/d/1J7ZyitaehfzV8mSbkPkhAwU1DLaCF6Tk/view?usp=sharing)

**Comment by JavaFactoryDev** [comment]
Hi HgeX, 
thank you for reporting this issue here, we will have a look at it.

Regards
Leonhard from MineAcademy

**Comment by kangarko** [comment]
Thanks, confirmed, fixed.

**Comment by HgeX** [comment]
Thank you! <3
