### ISSUE TITLE
Bring back the alias setting?

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/Confiscate#99]
The alias c: ... I'm not sure what this actually resolves to but can be used in the /sudo command as /sudo <player> c:<message> and that message will be shown in chat as though typed by that player.  By using 'c' as a hardcoded alias for confiscate, you disable this.  There is a work around as long as channels are enabled in CHC but I am basically the only one who can properly recall this command and use it.  

Also FYI the PowerNBT plugin - while still not updating on spigot, it appears to have a different github home than that one links:
https://github.com/Focusvity/PowerNBT/tree/0.9.1

Which would allow for offline inventory access.  Although I did find a small OpenInv bukkit plugin that accomplishes the same thing.   In the past this is all I wanted from Confiscate but now... the scan and removal of items enchanted beyond what should be possible is a thing I may need to use so as long as that stays a very fast/efficient thing that doesn't lag players on their tps I think I'll want to keep this around if it continues as a plugin.

**Comment by kangarko** [comment]
Hi there,

You can disable the /c alias by removing it from "Command_Aliases" key in settings.yml, so it will only end up with:

`Command_Aliases: [confiscate]`

You can do the same for ChatControl and any other plugin of us.

**Comment by mrcoffee1026** [comment]
Ah yes, weird it wasn't there as an option in the original config, but the edited one that shows up after it's been run once it was in that one.  And yeah a player of mine actually pinged me on discord about it or I'd never have seen that about the powernbt thing, i'd pretty much given up on that plugin ever working again but it's great that it does, so handy.
